create table positions (id integer not null, positionGroup varchar(255), positionName varchar (255), primary key (id));
create sequence positions_id start with 1;
create table technologies (id integer not null, technologyName varchar(255), primary key (id));
create sequence technologies_id start with 1;

insert into positions (id, positionGroup, positionName) values (nextval('positions_id'),'Development','Junior Software Engineer');
insert into positions (id, positionGroup, positionName) values (nextval('positions_id'),'Development','Software Engineer');
insert into positions (id, positionGroup, positionName) values (nextval('positions_id'),'Development','Senior Software Engineer');
insert into positions (id, positionGroup, positionName) values (nextval('positions_id'),'Development','System Architect');
insert into positions (id, positionGroup, positionName) values (nextval('positions_id'),'Development','Technical Lead');
insert into positions (id, positionGroup, positionName) values (nextval('positions_id'),'Management','Team Lead');
insert into positions (id, positionGroup, positionName) values (nextval('positions_id'),'Management','Project Manager');
insert into positions (id, positionGroup, positionName) values (nextval('positions_id'),'Management','Senior Project Manager / Program Manager');
insert into positions (id, positionGroup, positionName) values (nextval('positions_id'),'Management','Director of Engineering / Program Director');
insert into positions (id, positionGroup, positionName) values (nextval('positions_id'),'QA','Junior QA Engineer');
insert into positions (id, positionGroup, positionName) values (nextval('positions_id'),'QA','QA Engineer');
insert into positions (id, positionGroup, positionName) values (nextval('positions_id'),'QA','Senior QA Engineer');
insert into positions (id, positionGroup, positionName) values (nextval('positions_id'),'QA','QA Tech Lead');
insert into positions (id, positionGroup, positionName) values (nextval('positions_id'),'Other','DBA / Администратор баз данных');
insert into positions (id, positionGroup, positionName) values (nextval('positions_id'),'Other','Бизнес-аналитик');
insert into positions (id, positionGroup, positionName) values (nextval('positions_id'),'Other','Верстальщик');
insert into positions (id, positionGroup, positionName) values (nextval('positions_id'),'Other','Гейм-дизайнер');
insert into positions (id, positionGroup, positionName) values (nextval('positions_id'),'Other','Дизайнер');
insert into positions (id, positionGroup, positionName) values (nextval('positions_id'),'Other','Системный администратор');
insert into positions (id, positionGroup, positionName) values (nextval('positions_id'),'Other','Технический писатель');
insert into positions (id, positionGroup, positionName) values (nextval('positions_id'),'Other','Support');
insert into positions (id, positionGroup, positionName) values (nextval('positions_id'),'Other','HR');

insert into technologies (id, technologyName) values (nextval('technologies_id'),'APL');
insert into technologies (id, technologyName) values (nextval('technologies_id'),'C');
insert into technologies (id, technologyName) values (nextval('technologies_id'),'C#/.NET');
insert into technologies (id, technologyName) values (nextval('technologies_id'),'C++');
insert into technologies (id, technologyName) values (nextval('technologies_id'),'Delphi');
insert into technologies (id, technologyName) values (nextval('technologies_id'),'Flex/Flash/AIR');
insert into technologies (id, technologyName) values (nextval('technologies_id'),'Java');
insert into technologies (id, technologyName) values (nextval('technologies_id'),'JavaScript');
insert into technologies (id, technologyName) values (nextval('technologies_id'),'Objective-C');
insert into technologies (id, technologyName) values (nextval('technologies_id'),'Perl');
insert into technologies (id, technologyName) values (nextval('technologies_id'),'PHP');
insert into technologies (id, technologyName) values (nextval('technologies_id'),'Python');
insert into technologies (id, technologyName) values (nextval('technologies_id'),'Ruby/Rails');
insert into technologies (id, technologyName) values (nextval('technologies_id'),'Scala');
insert into technologies (id, technologyName) values (nextval('technologies_id'),'SQL');