CREATE TABLE positions (id INTEGER NOT NULL, positionGroup VARCHAR(255), positionName VARCHAR(255), PRIMARY KEY (id));
CREATE SEQUENCE positions_id START WITH 1;
CREATE TABLE technologies (id INTEGER NOT NULL, technologyName VARCHAR(255), PRIMARY KEY (id));
CREATE SEQUENCE technologies_id START WITH 1;

INSERT INTO positions (id, positionGroup, positionName) VALUES (nextval('positions_id'), 'Development', 'Junior Software Engineer');
INSERT INTO positions (id, positionGroup, positionName) VALUES (nextval('positions_id'), 'Development', 'Software Engineer');
INSERT INTO positions (id, positionGroup, positionName) VALUES (nextval('positions_id'), 'Development', 'Senior Software Engineer');
INSERT INTO positions (id, positionGroup, positionName) VALUES (nextval('positions_id'), 'Development', 'System Architect');
INSERT INTO positions (id, positionGroup, positionName) VALUES (nextval('positions_id'), 'Development', 'Technical Lead');
INSERT INTO positions (id, positionGroup, positionName) VALUES (nextval('positions_id'), 'Management', 'Team Lead');
INSERT INTO positions (id, positionGroup, positionName) VALUES (nextval('positions_id'), 'Management', 'Project Manager');
INSERT INTO positions (id, positionGroup, positionName) VALUES (nextval('positions_id'), 'Management', 'Senior Project Manager / Program Manager');
INSERT INTO positions (id, positionGroup, positionName) VALUES (nextval('positions_id'), 'Management', 'Director of Engineering / Program Director');
INSERT INTO positions (id, positionGroup, positionName) VALUES (nextval('positions_id'), 'QA', 'Junior QA Engineer');
INSERT INTO positions (id, positionGroup, positionName) VALUES (nextval('positions_id'), 'QA', 'QA Engineer');
INSERT INTO positions (id, positionGroup, positionName) VALUES (nextval('positions_id'), 'QA', 'Senior QA Engineer');
INSERT INTO positions (id, positionGroup, positionName) VALUES (nextval('positions_id'), 'QA', 'QA Tech Lead');
INSERT INTO positions (id, positionGroup, positionName) VALUES (nextval('positions_id'), 'Other', 'DBA / ������������� ��� ������');
INSERT INTO positions (id, positionGroup, positionName) VALUES (nextval('positions_id'), 'Other', '������-��������');
INSERT INTO positions (id, positionGroup, positionName) VALUES (nextval('positions_id'), 'Other', '�����������');
INSERT INTO positions (id, positionGroup, positionName) VALUES (nextval('positions_id'), 'Other', '����-��������');
INSERT INTO positions (id, positionGroup, positionName) VALUES (nextval('positions_id'), 'Other', '��������');
INSERT INTO positions (id, positionGroup, positionName) VALUES (nextval('positions_id'), 'Other', '��������� �������������');
INSERT INTO positions (id, positionGroup, positionName) VALUES (nextval('positions_id'), 'Other', '����������� ��������');
INSERT INTO positions (id, positionGroup, positionName) VALUES (nextval('positions_id'), 'Other', 'Support');
INSERT INTO positions (id, positionGroup, positionName) VALUES (nextval('positions_id'), 'Other', 'HR');

INSERT INTO technologies (id, technologyName) VALUES (nextval('technologies_id'), 'APL');
INSERT INTO technologies (id, technologyName) VALUES (nextval('technologies_id'), 'C');
INSERT INTO technologies (id, technologyName) VALUES (nextval('technologies_id'), 'C#/.NET');
INSERT INTO technologies (id, technologyName) VALUES (nextval('technologies_id'), 'C++');
INSERT INTO technologies (id, technologyName) VALUES (nextval('technologies_id'), 'Delphi');
INSERT INTO technologies (id, technologyName) VALUES (nextval('technologies_id'), 'Flex/Flash/AIR');
INSERT INTO technologies (id, technologyName) VALUES (nextval('technologies_id'), 'Java');
INSERT INTO technologies (id, technologyName) VALUES (nextval('technologies_id'), 'JavaScript');
INSERT INTO technologies (id, technologyName) VALUES (nextval('technologies_id'), 'Objective-C');
INSERT INTO technologies (id, technologyName) VALUES (nextval('technologies_id'), 'Perl');
INSERT INTO technologies (id, technologyName) VALUES (nextval('technologies_id'), 'PHP');
INSERT INTO technologies (id, technologyName) VALUES (nextval('technologies_id'), 'Python');
INSERT INTO technologies (id, technologyName) VALUES (nextval('technologies_id'), 'Ruby/Rails');
INSERT INTO technologies (id, technologyName) VALUES (nextval('technologies_id'), 'Scala');
INSERT INTO technologies (id, technologyName) VALUES (nextval('technologies_id'), 'SQL');