CREATE TABLE positions (id INTEGER NOT NULL, positionGroup VARCHAR(255), positionName VARCHAR(255), PRIMARY KEY (id));
CREATE SEQUENCE positions_id START WITH 1;
CREATE TABLE technologies (id INTEGER NOT NULL, technologyName VARCHAR(255), PRIMARY KEY (id));
CREATE SEQUENCE technologies_id START WITH 1;

INSERT INTO positions (id, positionGroup, positionName) VALUES (1, 'Development', 'Junior Software Engineer');
INSERT INTO positions (id, positionGroup, positionName) VALUES (2, 'Development', 'Software Engineer');
INSERT INTO positions (id, positionGroup, positionName) VALUES (3, 'Development', 'Senior Software Engineer');
INSERT INTO positions (id, positionGroup, positionName) VALUES (4, 'Development', 'System Architect');
INSERT INTO positions (id, positionGroup, positionName) VALUES (5, 'Development', 'Technical Lead');
INSERT INTO positions (id, positionGroup, positionName) VALUES (6, 'Management', 'Team Lead');
INSERT INTO positions (id, positionGroup, positionName) VALUES (7, 'Management', 'Project Manager');
INSERT INTO positions (id, positionGroup, positionName) VALUES (8, 'Management', 'Senior Project Manager / Program Manager');
INSERT INTO positions (id, positionGroup, positionName) VALUES (9, 'Management', 'Director of Engineering / Program Director');
INSERT INTO positions (id, positionGroup, positionName) VALUES (10, 'QA', 'Junior QA Engineer');
INSERT INTO positions (id, positionGroup, positionName) VALUES (11, 'QA', 'QA Engineer');
INSERT INTO positions (id, positionGroup, positionName) VALUES (12, 'QA', 'Senior QA Engineer');
INSERT INTO positions (id, positionGroup, positionName) VALUES (13, 'QA', 'QA Tech Lead');
INSERT INTO positions (id, positionGroup, positionName) VALUES (14, 'Other', 'DBA / Администратор баз данных');
INSERT INTO positions (id, positionGroup, positionName) VALUES (15, 'Other', 'Бизнес-аналитик');
INSERT INTO positions (id, positionGroup, positionName) VALUES (16, 'Other', 'Верстальщик');
INSERT INTO positions (id, positionGroup, positionName) VALUES (17, 'Other', 'Гейм-дизайнер');
INSERT INTO positions (id, positionGroup, positionName) VALUES (18, 'Other', 'Дизайнер');
INSERT INTO positions (id, positionGroup, positionName) VALUES (19, 'Other', 'Системный администратор');
INSERT INTO positions (id, positionGroup, positionName) VALUES (20, 'Other', 'Технический писатель');
INSERT INTO positions (id, positionGroup, positionName) VALUES (21, 'Other', 'Support');
INSERT INTO positions (id, positionGroup, positionName) VALUES (22, 'Other', 'HR');
ALTER SEQUENCE positions_id START WITH 23;

INSERT INTO technologies (id, technologyName) VALUES (1, 'APL');
INSERT INTO technologies (id, technologyName) VALUES (2, 'C');
INSERT INTO technologies (id, technologyName) VALUES (3, 'C#/.NET');
INSERT INTO technologies (id, technologyName) VALUES (4, 'C++');
INSERT INTO technologies (id, technologyName) VALUES (5, 'Delphi');
INSERT INTO technologies (id, technologyName) VALUES (6, 'Flex/Flash/AIR');
INSERT INTO technologies (id, technologyName) VALUES (7, 'Java');
INSERT INTO technologies (id, technologyName) VALUES (8, 'JavaScript');
INSERT INTO technologies (id, technologyName) VALUES (9, 'Objective-C');
INSERT INTO technologies (id, technologyName) VALUES (10, 'Perl');
INSERT INTO technologies (id, technologyName) VALUES (11, 'PHP');
INSERT INTO technologies (id, technologyName) VALUES (12, 'Python');
INSERT INTO technologies (id, technologyName) VALUES (13, 'Ruby/Rails');
INSERT INTO technologies (id, technologyName) VALUES (14, 'Scala');
INSERT INTO technologies (id, technologyName) VALUES (15, 'SQL');
ALTER SEQUENCE technologies_id START WITH 16;